index: pe
indexTest: Person Entity
type: product
typeText: Product
fixedColumns: 2
doc:
  params:
    query: SELECT * FROM pe_prod_mstr
    id: pe_prod_mstr.pr_id
    chunkSize: 100
    orderBy: pe_prod_mstr.unique_id
  ProductID:
    field: pe_prod_mstr.pr_id
    type: string
    text: Product ID
    facet: false
  PeId:
    field: pe_prod_mstr.pe_id
    type: string
    text: PE ID
    facet: true
  ProductStatus:
    field: pe_prod_mstr.prod_status
    type: string
    text: Product Status
    facet: true
  ProductTitle:
    field: pe_prod_mstr.prod_title
    type: string
    text: Product Title
    facet: false
  ProductDescription:
    field: pe_prod_mstr.prod_desc
    type: string
    text: Product Description
    facet: false
  Inventory:
    field: pe_prod_mstr.inventory
    type: float
    text: Inventory
    facet: true
  UpdateWhen:
    field: pe_prod_mstr.update_when
    type: date
    text: Update When
    facet: true
  UniqueKey:
    field: pe_prod_mstr.unique_key
    type: string
    text: Update Key
    facet: false