index: pe
indexText: Person Entity
type: name
typeText: Vendor
fixedColumns: 2
params:
  query: SELECT * FROM pe_name_mstr
  id: pe_name_mstr.pe_id
  orderBy: pe_name_mstr.unique_id
  chunkSize: 100
doc:
  PeId:
    field: pe_name_mstr.pe_id
    type: string
    text: PE ID
    facet: false
  FullName:
    field: pe_name_mstr.name
    type: string
    text: Full Name
    facet: false
  Status:
    field: pe_name_mstr.pe_id_status
    type: string
    text: Status
    facet: true
    code:
      key: pePeMasterStatus
      where:
  FirstName:
    field: pe_name_mstr.name_first
    type: string
    text: First Name
    facet: false
  MiddleName:
    field: pe_name_mstr.name_middle
    type: string
    text: Middle Name
    facet: false
  LastName:
    field: pe_name_mstr.name_last
    type: string
    text: Last Name
    facet: false
  Url:
    field: pe_name_mstr.pe_url
    type: string
    text: Url
    facet: false
  SecurityCode:
    field: pe_name_mstr.security_cd
    type: string
    text: Security Code
    facet: true
    code:
      key: peCommonCodes
      where:
        - $PEOW
  SelCode1:
    field: pe_name_mstr.pe_sel_cd1
    type: string
    text: Select Code 1
    facet: true
  SelCode2:
    field: pe_name_mstr.pe_sel_cd2
    type: string
    text: Select Code 2
    facet: true
  AffCode:
    field: pe_name_mstr.affil_cd
    type: string
    text: Affiliation Code
    facet: true
    code:
      key: peAffiliateCode
      where:
  Address:
    type: nested
    text: Adresses
    params:
      query: SELECT * FROM pe_address_dtl INNER JOIN pe_name_mstr ON pe_address_dtl.pe_id = pe_name_mstr.pe_id
      id: pe_address_dtl.pe_id
      orderBy: pe_address_dtl.unique_id
      chunkSize: 100
    doc:
      PeId:
        field: pe_address_dtl.pe_id
        type: string
        text: PE ID
        facet: false
      AdressCode:
        field: pe_address_dtl.pe_addr_cd
        type: string
        text: Code
        facet: true
        code:
          key: peCommonCodes
          where:
            - $PEAC
      Street:
        field: pe_address_dtl.st1
        type: string
        text: Address
        facet: false
        function:
          type: concatStrings
          fields:
            - pe_address_dtl.st1
            - '|, '
            - pe_address_dtl.st2
      City:
        field: pe_address_dtl.city
        type: string
        text: City
        facet: true
      State:
        field: pe_address_dtl.state
        type: string
        text: State
        facet: true
        code:
          key: peCommonCodes
          where:
            - $PEST
      Zip:
        field: pe_address_dtl.zip
        type: integer
        text: Zip
        facet: false
      ZipCalculated:
        field: pe_address_dtl.zip
        type: integer
        text: Zip Calc
        facet: false
        function:
          type: equation
          fields:
            - pe_address_dtl.zip
            - '|1000'
            - '|/'
            - '|2'
      UpdateWhen:
        field: pe_address_dtl.update_when
        type: date
        text: Update When
        facet: false
      UniqueKey:
        field: pe_address_dtl.unique_key
        type: string
        text: Unique Key
        facet: false
  Email:
    type: nested
    text: Email
    params:
      query: SELECT * FROM pe_email_dtl INNER JOIN pe_name_mstr ON pe_email_dtl.pe_id = pe_name_mstr.pe_id
      id: pe_email_dtl.pe_id
      orderBy: pe_email_dtl.unique_id
      chunkSize: 100
    doc:
      PeId:
        field: pe_email_dtl.pe_id
        type: string
        text: PE ID
        facet: false
      EmailType:
        field: pe_email_dtl.email_type_cd
        type: string
        text: Type
        facet: true
        code:
          key: peCommonCodes
          where:
            - $PEET
      EmailAddressCode:
        field: pe_email_dtl.pe_addr_cd
        type: string
        text: Address Code
        facet: true
        code:
          key: peCommonCodes
          where:
            - $PEAC
      Email:
        field: pe_email_dtl.email_addr
        type: string
        text: Email Address
        facet: false
      UpdateWhen:
        field: pe_email_dtl.update_when
        type: date
        text: Update When
        facet: false
      UniqueKey:
        field: pe_email_dtl.unique_key
        type: string
        text: Update When
        facet: false
  UpdateWhen:
    field: pe_name_mstr.update_when
    type: date
    text: Update When
    facet: true
  UniqueKey:
    field: pe_name_mstr.unique_key
    type: string
    text: Unique Key
    facet: false