index: hr
indexText: Human Resources
type: employee
typeText: Employee
fixedColumns: 1
doc:
  params:
    query: SELECT * FROM hr_empmstr
    id: hr_empmstr.id
    orderBy: hr_empmstr.unique_id
  EmpID:
    field: hr_empmstr.id
    type: string
    text: Employee ID
    facet: false
  HRStatus:
    field: hr_empmstr.status
    type: string
    text: HR Status
    facet: true
    code:
      key: hrEmployeeStatus
      where:
        - Entity
  PYStatus:
    field: hr_empmstr.py_stat
    type: string
    text: PY Status
    facet: true
    code:
      key: hrPYStatus
      where:
  FullName:
    field: hr_empmstr.name
    type: string
    text: Full Name
    facet: false
  FirstName:
    field: hr_empmstr.fname
    type: string
    text: First Name
    facet: false
  MiddleName:
    field: hr_empmstr.mname
    type: string
    text: Middle Name
    facet: false
  LastName:
    field: hr_empmstr.lname
    type: string
    text: Last Name
    facet: false
  Type:
    field: hr_empmstr.type
    type: string
    text: Type
    facet: true
    code:
      key: hrEmployeeType
      where:
        - Entity
  BargUnit:
    field: hr_empmstr.barg_unit
    type: string
    text: Bargaining Unit
    facet: true
    code:
      key: hrBargUnit
      where:
        - Entity
  Division:
    field: hr_empmstr.division
    type: string
    text: Division
    facet: true
    code:
      key: hrDivision
      where:
        - Entity
  Department:
    field: hr_empmstr.dept
    type: string
    text: Department
    facet: true
    code:
      key: hrDepartment
      where:
        - Entity
  BirthDt:
    field: hr_empmstr.dob
    type: date
    text: Birth Date
    facet: true
  HireDt:
    field: hr_empmstr.hdt
    type: date
    text: Hire Date
    facet: true
  Entity:
    field: hr_empmstr.entity
    type: string
    text: Entity
    facet: true
    code:
      key: hrEntity
  UpdateWhen:
    field: hr_empmstr.update_when
    type: date
    text: Update When
    facet: true
  UniqueKey:
    field: hr_empmstr.unique_key
    type: string
    text: Unique Key
    facet: false