doc:
  Url: DEPRECATED
  extraFieldMinor2:
    field: pe_name_mstr.extra_field2
    type: float
    text: Extra Minor 2
    facet: true
  extraFieldMinor3:
    field: pe_name_mstr.extra_field3
    type: float
    text: Extra Minor 3
    facet: true
#subDocs:
#  - SKIP
#  - params:
#      url: pe_email_dtl.url